name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  increment-version:
    name: Increment Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.NEW_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Increment version
        id: set-version
        run: |
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.2.0")
          MAJOR=$(echo $VERSION | awk -F. '{print $1}' | sed 's/v//')
          MINOR=$(echo $VERSION | awk -F. '{print $2}')
          PATCH=$(echo $VERSION | awk -F. '{print $3}')
          PATCH=$((PATCH + 1))
          if [ "$PATCH" -gt 9 ]; then
            PATCH=0
            MINOR=$((MINOR + 1))
          fi
          NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          echo "::set-output name=NEW_VERSION::$NEW_VERSION"

      # - name: Create Git tag
      #   run: |
      #     git tag ${{ steps.set-version.outputs.NEW_VERSION }}
      #     git push origin ${{ steps.set-version.outputs.NEW_VERSION }}

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    needs: increment-version
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm run install-all

      - name: Run common build
        run: npm run build

      - name: Run Linux build
        run: npm run electron:build:linux:arm64

      - name: Rename Linux artifacts
        run: |
          ls -al ./dist_electron
          mv "./dist_electron/MoeKoe Music-1.2.0-arm64.AppImage" "./MoeKoe_Music_${{ needs.increment-version.outputs.version }}_arm64.AppImage"
          mv "./dist_electron/moekoemusic_1.2.0_arm64.deb" "./moekoemusic_${{ needs.increment-version.outputs.version }}_arm64.deb"

      - name: Upload Linux artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.increment-version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "Release ${{ needs.increment-version.outputs.version }}"
          body: ${{ env.COMMIT_MESSAGE }}
          prerelease: true
          files: |
            ./MoeKoe_Music_${{ needs.increment-version.outputs.version }}_arm64.AppImage
            ./moekoemusic_${{ needs.increment-version.outputs.version }}_arm64.deb
