name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  increment-version:
    name: Increment Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.NEW_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Increment version
        id: set-version
        run: |
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.2.0")
          MAJOR=$(echo $VERSION | awk -F. '{print $1}' | sed 's/v//')
          MINOR=$(echo $VERSION | awk -F. '{print $2}')
          PATCH=$(echo $VERSION | awk -F. '{print $3}')
          PATCH=$((PATCH + 1))
          if [ "$PATCH" -gt 9 ]; then
            PATCH=0
            MINOR=$((MINOR + 1))
          fi
          NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

  build-linux-arm64:
    name: Build for Linux (ARM64)
    runs-on: ubuntu-latest
    needs: increment-version
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Up QEMU (for ARM64 build)
        uses: docker/setup-qemu-action@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm run install-all

      - name: Run common build
        run: npm run build

      - name: Run Linux ARM64 build
        run: npm run electron:build -- --linux --arm64

      - name: List files in dist_electron directory
        run: ls -al ./dist_electron  # 列出 dist_electron 目录中的文件

      - name: Rename Linux artifacts
        run: |
          mv "./dist_electron/MoeKoe Music-1.2.0-arm64.AppImage" "./MoeKoe_Music_${{ needs.increment-version.outputs.version }}_arm64.AppImage"
          mv "./dist_electron/moekoemusic_1.2.0_arm64.deb" "./moekoemusic_${{ needs.increment-version.outputs.version }}_arm64.deb"

      - name: Upload Linux ARM64 artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "Release ${{ env.NEW_VERSION }}"
          body: "Auto-generated ARM64 release ${{ env.NEW_VERSION }}"
          prerelease: true
          files: |
            ./MoeKoe_Music_${{ env.NEW_VERSION }}_arm64.AppImage
            ./moekoemusic_${{ env.NEW_VERSION }}_arm64.deb
